### ISSUE TITLE
(leaking threads?) VBMS checks sometimes show older status

### ISSUE THREAD

**Issue by lisac-usds** [department-of-veterans-affairs/caseflow-monitor#58]
## Description

Observed, just minutes apart: 

11:46
<img width="896" alt="screen shot 2018-05-14 at 11 46 23" src="https://user-images.githubusercontent.com/31673962/40008130-954f41b8-576c-11e8-943c-2de831cce892.png">

11:47
<img width="1016" alt="screen shot 2018-05-14 at 11 47 43" src="https://user-images.githubusercontent.com/31673962/40008157-a8496316-576c-11e8-8607-1be76fe07218.png">

11:49
<img width="1023" alt="screen shot 2018-05-14 at 11 49 06" src="https://user-images.githubusercontent.com/31673962/40008251-df41b904-576c-11e8-82bc-25a32df8b68e.png">

Can we explain why this is happening?

**Comment by askldjd** [comment]
I saw a lot of errors in the log files

```
W, [2018-05-14T05:15:14.751289 #2917]  WARN -- : ["/opt/caseflow-monitor/src/vendor/bundle/ruby/2.3.0/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'", "/opt/caseflow-monitor/src/vendor/bundle/ruby/2.3.0/gems/socksify-1.7.1/lib/socksify.rb:178:in `initialize'", "/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:880:in `open'", "/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'", "/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'", "/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:878:in `connect'", "/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start'", "/opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:852:in `start'", "/opt/caseflow-monitor/src/vendor/bundle/ruby/2.3.0/gems/dogapi-1.29.0/lib/dogapi/common.rb:97:in `connect'", "/opt/caseflow-monitor/src/vendor/bundle/ruby/2.3.0/gems/dogapi-1.29.0/lib/dogapi/common.rb:117:in `request'", "/opt/caseflow-monitor/src/vendor/bundle/ruby/2.3.0/gems/dogapi-1.29.0/lib/dogapi/v1/metric.rb:24:in `upload'", "/opt/caseflow-monitor/src/vendor/bundle/ruby/2.3.0/gems/dogapi-1.29.0/lib/dogapi/v1/metric.rb:29:in `submit_to_api'", "/opt/caseflow-monitor/src/vendor/bundle/ruby/2.3.0/gems/dogapi-1.29.0/lib/dogapi/v1/metric.rb:48:in `submit'", "/opt/caseflow-monitor/src/vendor/bundle/ruby/2.3.0/gems/dogapi-1.29.0/lib/dogapi/facade.rb:94:in `emit_points'", "/opt/caseflow-monitor/src/vendor/bundle/ruby/2.3.0/gems/dogapi-1.29.0/lib/dogapi/facade.rb:67:in `emit_point'", "/opt/caseflow-monitor/src/app/services/monitor_service.rb:191:in `update_datadog_metrics'", "/opt/caseflow-monitor/src/app/services/monitor_service.rb:74:in `failed'", "/opt/caseflow-monitor/src/app/jobs/monitor_job.rb:127:in `rescue in block in run_query'", "/opt/caseflow-monitor/src/app/jobs/monitor_job.rb:113:in `block in run_query'"]
```

I restarted the application and the error went away. Something tells me that we might be leaking threads since these errors persists throughout the log file.

**Comment by lisac-usds** [comment]
The fix might involve refining [setup_zombie_monitor](https://github.com/department-of-veterans-affairs/caseflow-monitor/blob/7ff956a89a5abf2255af97e1d57c116a603b68f8/app/jobs/monitor_job.rb#L141) .

Another approach, this one less precise but easy to implement: deploy Monitor frequently.
